"use client";
import {useEffect,useState} from "react";
function monday(){const d=new Date();const diff=(d.getDay()+6)%7;d.setDate(d.getDate()-diff);return d.toISOString().slice(0,10)}
async function get(path:string){const r=await fetch("/api/team/"+path,{cache:"no-store",credentials:"same-origin"});if(!r.ok)throw new Error(path+" HTTP "+r.status);return r.json()}
export default function ManagerPage(){
 const[d,setD]=useState<any>(null);const[e,setE]=useState("");
 useEffect(()=>{Promise.all([get("manager/overview"),get("manager/weekly-review?week_start="+monday()),get("manager/match-quality"),get("margin/management-summary")]).then(([overview,weekly,quality,margin])=>setD({overview,weekly,quality,margin})).catch(x=>setE(x.message))},[]);
 if(e)return <main className="page"><div className="adminError"><b>Manager view unavailable</b><span>{e}</span><p>This page requires a Manager or Admin account.</p></div></main>;
 if(!d)return <main className="page"><div className="adminLoading">Loading Manager…</div></main>;
 const o=d.overview||{},q=d.quality||{},m=d.margin||{},mt=m.totals||{};
 return <main className="page managerPage"><div className="pageHead"><div><small>Manager command center</small><h1>Team Overview</h1><p>Workload, weekly performance, follow-ups and match quality.</p></div><div className="pageActions"><a href="/">Today</a><a href="/jobs">Jobs</a><a href="/candidates">Candidates</a></div></div>
  <div className="adminMetricGrid"><article><strong>{o.totals?.active_recruiters??0}</strong><b>Active recruiters</b><span>In teams you manage</span></article><article><strong>{o.totals?.work_items??0}</strong><b>Work items</b><span>Current assigned workload</span></article><article><strong>{o.totals?.open_followups??0}</strong><b>Open follow-ups</b><span>{o.totals?.overdue_followups??0} overdue</span></article><article><strong>{q.feedback_count??0}</strong><b>Match feedback</b><span>Measurement-only pilot feedback</span></article><article><strong>{q.pilot_target?.minimum_feedback??100}</strong><b>Pilot target</b><span>Minimum feedback before ranking decisions</span></article><article><strong>{(q.negative_reasons||[])[0]?.key||"—"}</strong><b>Top gap reason</b><span>{(q.negative_reasons||[])[0]?.count||0} negative reviews</span></article></div>
  <section className="panelBox"><small>Gross Margin & Rate Packages</small><div className="gmManagerGrid"><article><strong>{mt.current_packages??0}</strong><b>Current packages</b><span>Latest recruiter version</span></article><article><strong>{((mt.average_gm_percent??0)*100).toFixed(1)}%</strong><b>Average GM</b><span>Across current packages</span></article><article><strong>{mt.finalized??0}</strong><b>Finalized rates</b><span>Recruiter-owned decisions</span></article><article><strong>{mt.discussion_required??0}</strong><b>Needs discussion</b><span>Commercial guidance required</span></article><article><strong>{mt.negative_gm??0}</strong><b>Negative GM</b><span>Executive exception path</span></article></div>{(m.recent||[]).length?<table className="adminTable"><thead><tr><th>Recruiter</th><th>Profile</th><th>GM</th><th>Status</th><th>Lifecycle</th></tr></thead><tbody>{m.recent.slice(0,12).map((x:any)=><tr key={x.id}><td>{x.recruiter_name}</td><td>{String(x.calculation_profile||"").replaceAll("_"," ")}</td><td>{((Number(x.result_payload?.gross_margin_percent||0))*100).toFixed(1)}%</td><td>{String(x.guideline_status||"").replaceAll("_"," ")}</td><td>{String(x.lifecycle_status||"").replaceAll("_"," ")}</td></tr>)}</tbody></table>:<div className="emptyState">No rate packages are available yet.</div>}</section>
  <section className="panelBox"><small>Recruiter workload</small><table className="adminTable"><thead><tr><th>Recruiter</th><th>Work items</th><th>Open follow-ups</th><th>Overdue</th></tr></thead><tbody>{(o.recruiters||[]).map((r:any)=><tr key={r.id}><td>{r.display_name}</td><td>{r.work_items}</td><td>{r.open_followups}</td><td>{r.overdue_followups}</td></tr>)}</tbody></table></section>
  <section className="panelBox"><small>Weekly goal vs actual</small><table className="adminTable"><thead><tr><th>Recruiter</th><th>Submissions</th><th>Interviews</th><th>Closures</th><th>Priority jobs</th></tr></thead><tbody>{(d.weekly.recruiters||[]).map((r:any)=><tr key={r.id}><td>{r.display_name}</td><td>{r.actuals?.submissions??0} / {r.targets?.submissions??0}</td><td>{r.actuals?.interviews??0} / {r.targets?.interviews??0}</td><td>{r.actuals?.closures??0} / {r.targets?.closures??0}</td><td>{r.targets?.priority_jobs??0}</td></tr>)}</tbody></table></section>
  <section className="panelBox"><small>Match quality by score band</small><div className="qualityBands">{(q.score_bands||[]).map((b:any)=><article key={b.key}><strong>{b.agreement_rate??0}%</strong><b>{b.key}</b><span>{b.positive??0} positive / {b.total??0} reviewed</span></article>)}</div><h3>Negative reasons</h3><div className="chips">{(q.negative_reasons||[]).map((x:any)=><span key={x.key}>{x.key}: {x.count}</span>)}</div></section>
 </main>
}